### PR TITLE
Added a block_palette attribute to the chunk class

### PR DESCRIPTION
**Pull request by gentlegiantJGC**
Currently the world palette and chunk classes are distinct things. Without the world palette the block indexes in the Chunk class are meaningless. I suggest we add an attribute to the chunk class that stores the block palette so that the data in the Chunk class has meaning without additional data. All chunks stored in the World class should use the same world block palette so the change is relatively small but this also enables other benefits.

During translation the world palette needs passing into the conversion code as an extra input for for it to add the block states to. I feel it would be better for the conversion code to return a chunk that has a local palette and at the point it is added to the world the data would be remapped to point to the global palette. This would mean the global palette would not need to be passed into the conversion code as an extra input as it would be an attribute of the chunk.

I need to look into how we are handling biomes but I believe the same issue applies there as well. This would mean we won't need to change the translation API to handle other indexed data like biomes as it will be attributes of the chunk.

This would also help with copying chunks between world classes because the add_chunk method could automatically reassign the block palette and change the indexes rather than the calling code having to do it each time.

### CODE REVIEW

**Comment by gentlegiantJGC** [comment]
This will also solve #74

**Comment by gentlegiantJGC** [comment]
I wasn't sure that the correct way to handle that was. `BaseFormatWraper` is subclassed by both the `WorldFormatWrapper` and the structure format wrappers. It means `BaseFormatWraper` can't contain the dimension input. `WorldFormatWrapper` adds that

**Comment by gentlegiantJGC** [comment]
To better explain my last message now that I am on my PC:

The [BaseFormatWrapper](https://github.com/Amulet-Team/Amulet-Core/blob/palette_rewrite/amulet/api/wrapper/format_wrapper.py#L148) implements a generic API that the others can expand upon.

Structures do not have dimensions so it doesn't make sense to have to specify a dimension input when getting a chunk so it just uses the default API.

Worlds have dimensions so they also need a [dimension input](https://github.com/Amulet-Team/Amulet-Core/blob/palette_rewrite/amulet/api/wrapper/world_format_wrapper.py#L88).

The format checker doesn't like it because I don't think you are supposed to modify the inputs of methods in subclasses but it is valid python. As far as I am concerned WorldFormatWrapper and StructureFormatWrapper could be different classes with no common base but they share most of the logic so it made sense.

I think you could make dimension a key word argument which would make it happy but I want the dimension to be compulsory so writers of operations don't get confused why it is getting different data. This way it will just tell them it is required.

**Comment by gentlegiantJGC** [comment]
I will merge these changes now. The signature issue existed before this pull request so you can fix that as a separate issue if you like.

**Comment by Podshot** [comment]
That's a fair point, it makes sense that it deviates due the presence of dimensions, so I think it's fine being left in as is

**Pull request merged**
