### PR TITLE
Fix platform specific cython

### PR DESCRIPTION
**Pull request by 0dminnimda**

### CODE REVIEW

**Comment by gentlegiantJGC** [comment]
Thanks for the suggestions. I think that moving it to a separate file probably is the best option.
It looks like __unix__ does not catch Apple platforms like I thought it would.

I will look into merging these changes into the new repository.

**Comment by 0dminnimda** [comment]
> I will look into merging these changes into the new repository.

I am a bit confused by the structure of the project. Can you explain?

**Comment by 0dminnimda** [comment]
Also, It probably would be nicer if I were to create a pr into the new repo.

**Comment by gentlegiantJGC** [comment]
I was in the process of moving this component to a new repository before I wrote on the cython issue.
If I had known you were going to create a pull request I would have let you know.

I haven't used any of your actual code. I just moved my own code to a different file.
<https://github.com/Amulet-Team/Amulet-LevelDB/commit/0880733be5fc1659338c6699e21edfce8cf93e86>

**Comment by 0dminnimda** [comment]
It's ok
More projects are moving from using this deprecated feature. And it's nice to support this change

**Pull request closed without merging**
