### PR TITLE
Implement basic player data system

### PR DESCRIPTION
**Pull request by Podshot**
This system allows for a flexible way to access player data as it's stored by both the Java/anvil and Bedrock formats.

### Changes

- `World` objects now have a `player_manager` attribute
- `PlayerManager` objects allow for the following functions and abstracts away the differences in how each format stores players
  - Getting the list of all player UUIDs present in the world
  - Get the player data for a specific player
  - Getting the local/single player data
- 'Player' objects abstract away how each format stores it's individual player data
  - Currently only `position` and `rotation` are implemented and are read-only

### CODE REVIEW

**Comment by gentlegiantJGC** [comment]
I will have a better look over this tomorrow.
We should have a better discussion on project structure. My initial thought is to have the platform specific logic within the world_interface section rather than in api but keep the base class in api

**Comment by gentlegiantJGC** [comment]
We should probably open another discussion on how we intend to handle modification of this data. Currently the undo/redo system is purely chunk based and modification of player data would need to be tied into that. The same applies to everything else not chunk based. (I know this is read only but worth thinking ahead to that)

It would be preferable for the World class to have its own player manager system separate to the one that interacts with the data on disk. This means it can handle undoing and redoing and on save the data gets pushed to disk through the disk class. The specifics I am not too sure on.

I would put the World based player manager in `api.world`
I would put the base class of the player data interface in `api.wrapper.global` and all other global interface base classes would go into there.
The version based player data interfaces would go in `world_interface.global.group` and the format classes would pick the ones they want to use.

**Comment by Podshot** [comment]
@gentlegiantJGC I think I have a possible idea to improve/extend our history system, but I need to work/think on it a bit more before purposing it. 
From what you currently described with the layout/organization of the classes and how I understand it, that sounds pretty good to me, I can make those changes sometime in the next few days

**Comment by gentlegiantJGC** [comment]
I am going to close this and open a draft for your new version

**Pull request closed without merging**
